apiVersion: frrk8s.metallb.io/v1beta1
kind: FRRConfiguration
metadata: # kpt-merge: frr-k8s-system/site-router-config
  name: site-router-config
  namespace: frr-k8s-system
  annotations:
    internal.kpt.dev/upstream-identifier: 'frrk8s.metallb.io|FRRConfiguration|frr-k8s-system|site-router-config'
spec:
  raw:
    priority: 5
    rawConfig: FRR_SITE_ROUTER_CONFIG
