apiVersion: fn.kpt.dev/v1alpha1
kind: ApplyReplacements
metadata: # kpt-merge: /propagate-name
  name: propagate-name
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: 'fn.kpt.dev|ApplyReplacements|default|propagate-name'
replacements:
- source:
    kind: WorkloadCluster
    name: workload-cluster
    fieldPath: spec.clusterName
  targets:
  - select:
      kind: NFDeployment
    fieldPaths:
    - metadata.name
    options:
      delimiter: '-'
      index: 1
