apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata: # kpt-merge: amf-example/amf-example
  name: amf-example
  namespace: amf-example
  annotations:
    internal.kpt.dev/upstream-identifier: 'workload.nephio.org|NFDeployment|amf-example|amf-example'
spec:
  provider: amf.openairinterface.org
  capacity:
    maxSubscribers: 1000
  interfaces:
  - name: n2
    ipv4:
      address: AMF_N2_IP
      gateway: AMF_N2_GW
    vlanID: 30
  networkInstances:
  - name: vpc-ran
    interfaces:
    - n2
  parametersRefs:
  - name: oai-amf-config
    apiVersion: workload.nephio.org/v1alpha1
    kind: NFConfig
