apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata: # kpt-merge: smf-example/smf-core-n4
  name: smf-core-n4
  namespace: oai-core
  annotations:
    internal.kpt.dev/upstream-identifier: k8s.cni.cncf.io|NetworkAttachmentDefinition|smf-example|smf-core-n4
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "smf-core-n4",
      "plugins": [
        {
          "type": "macvlan",
          "capabilities": {
            "ips": true
          },
          "master": "mltus_ens19_107",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "routes": [
              {
                "dst": "192.168.51.0/24",
                "gw": "192.168.56.1"
              }
            ]
          }
        }
      ]
    }
