apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata: # kpt-merge: flux-system/openebs
  name: openebs
  namespace: flux-system
  annotations:
    internal.kpt.dev/upstream-identifier: 'source.toolkit.fluxcd.io|HelmRepository|flux-system|openebs'
spec:
  url: https://openebs.github.io/charts
  interval: 5m
