apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: frr-k8s-system/frr-init-conf
  name: frr-init-conf
  namespace: frr-k8s-system
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|frr-k8s-system|frr-init-conf'
data:
  frr-init.sh: |
    sleep 20
    ip link add dev n2vrf type vrf table 1
    ip link add dev n4vrf type vrf table 2
    ip link set dev n2vrf up
    ip link set dev n4vrf up
    ip link set dev n2 master n2vrf
    ip link set dev n2uplink master n2vrf
    ip link set dev n4 master n4vrf
    ip link set dev n4uplink master n4vrf
