apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: frr-k8s-system/frr-init-conf
  name: frr-init-conf
  namespace: frr-k8s-system
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|frr-k8s-system|frr-init-conf'
data:
  frr-init.sh: FRR_VPP_INT_CONFIG
