apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: frr-k8s-system/vpp-startup-conf
  name: vpp-startup-conf
  namespace: frr-k8s-system
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|frr-k8s-system|vpp-startup-conf'
data:
  startup.conf: |
    unix {
      nodaemon
      log /var/log/vpp/vpp.log
      cli-listen /run/vpp/cli.sock
      gid vpp
      poll-sleep-usec 1000
      exec /etc/vpp/bootstrap.vpp
    }

    api-trace { on }
    api-segment { gid vpp }
    socksvr { default }

    memory {
      main-heap-size 512M
      main-heap-page-size default-hugepage
    }

    buffers {
      buffers-per-numa 128000
      default data-size 2048
      page-size default-hugepage
    }

    statseg {
      size 1G
      page-size default-hugepage
      per-node-counters off
    }

    plugins {
      plugin linux_nl_plugin.so { enable }
      plugin linux_cp_plugin.so { enable }
      plugin dpdk_plugin.so { enable }
    }

    logging {
      default-log-level info
      default-syslog-log-level notice
      class linux-cp { rate-limit 10000 level debug syslog-level debug }
      class linux-nl { rate-limit 10000 level debug syslog-level debug }
    }

    dpdk {
     dev 0000:00:14.0 {name dpdk0}
    }
---
apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: frr-k8s-system/vpp-init-conf
  name: vpp-init-conf
  namespace: frr-k8s-system
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|frr-k8s-system|vpp-init-conf'
data:
  bootstrap.vpp: "lcp lcp-sync on\nlcp lcp-auto-subint on\nip table add 1\nip table add 2              \ncreate sub-interfaces dpdk0 106\ncreate sub-interfaces dpdk0 107\nset interface ip table dpdk0.106 1\nset interface ip table dpdk0.107 2\nset interface state dpdk0 up\nset interface state dpdk0.106 up\nset interface state dpdk0.107 up\nlcp create dpdk0 host-if dpdk0\nlcp create dpdk0.106 host-if n2\nlcp create dpdk0.107 host-if n4\nset interface ip address dpdk0.106 192.168.55.1/24\nset interface ip address dpdk0.107 192.168.56.1/24\n"
